name: Pull Request

on:
    pull_request_target:

permissions:
    contents: write
    pull-requests: write

jobs:
    Duster:
        name: Duster
        uses: EncoreDigitalGroup/.github/.github/workflows/dusterFixBlame.yml@v1
        permissions:
            contents: write
            pull-requests: write
    StaticAnalysis:
        needs: Duster
        name: StaticAnalysis
        uses: EncoreDigitalGroup/.github/.github/workflows/larastan.yml@v1
        with:
            phpVersion: '8.3'
            branch: ${{ github.head_ref }}
    Test:
        needs: StaticAnalysis
        name: Test
        uses: EncoreDigitalGroup/.github/.github/workflows/pest.yml@v1
    AutoMerge:
        needs: StaticAnalysis
        name: AutoMerge
        uses: EncoreDigitalGroup/.github/.github/workflows/dependabotAutoMerge.yml@v1
